"""Create email_history table

Revision ID: bdc4e79ec201
Revises: 
Create Date: 2025-08-22 23:29:41.603741

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bdc4e79ec201'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_email', sa.String(), nullable=False),
    sa.Column('to_recipients', sa.String(), nullable=False),
    sa.Column('cc_recipients', sa.String(), nullable=True),
    sa.Column('bcc_recipients', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('attachment_name', sa.String(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_history_id'), 'email_history', ['id'], unique=False)
    op.drop_index(op.f('ix_users_display_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('display_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reset_token', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reset_token_expires', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_display_name'), 'users', ['display_name'], unique=False)
    op.drop_index(op.f('ix_email_history_id'), table_name='email_history')
    op.drop_table('email_history')
    # ### end Alembic commands ###
